// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx ts-node --project tsconfig.dev.json --require tsconfig-paths/register src/db/seeds/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
